import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../core/api.dart'; import '../../core/models.dart'; import '../../core/downloads.dart';
import '../../core/progress.dart';

class WatchPage extends StatefulWidget {
  const WatchPage({super.key,required this.title,required this.api,this.episode});
  final TitleItem title; final ApiClient api; final EpisodeItem? episode;
  @override State<WatchPage> createState()=>_WatchPageState();
}
class _WatchPageState extends State<WatchPage>{
  List<EpisodeItem> eps=[]; List<StreamOption> streams=[]; VideoPlayerController? player; int selected=1; double speed=1; int streamIndex=0; bool loading=true; String message='';
  @override void initState(){super.initState(); selected=widget.episode?.number??1; load();}
  Future<void> load() async {try{final e=await widget.api.episodes(widget.title.id); if(mounted)setState((){eps=e;loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
  Future<void> play() async {setState(()=>message='Finding stream…');try{final s=await widget.api.streams(titleId:widget.title.id,episode:selected);if(s.isEmpty){setState(()=>message='No playable stream returned by the configured API.');return;}streams=s;streamIndex=0;await _openStream(s.first);}catch(e){if(mounted)setState(()=>message='Unable to load stream.');}}
  Future<void> _openStream(StreamOption s) async {try{player?.removeListener(_saveProgress);await player?.dispose();final p=VideoPlayerController.networkUrl(Uri.parse(s.url),httpHeaders:s.headers);await p.initialize();await p.setPlaybackSpeed(speed);await p.play();p.addListener(_saveProgress);if(mounted)setState(()=>player=p);}catch(_){if(mounted)setState(()=>message='Player could not open this source.');}}
  Future<void> download() async {if(streams.isEmpty)await play();if(streams.isEmpty)return;final s=streams[streamIndex];if(s.url.contains('.m3u8')){if(await canLaunchUrl(Uri.parse(s.url)))await launchUrl(Uri.parse(s.url),mode:LaunchMode.externalApplication);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('This source is HLS. Opened the source externally; direct file downloads require a media downloader.')));return;}final safe=widget.title.name.replaceAll(RegExp(r'[^a-zA-Z0-9._-]+'),'_');final path=await DownloadManager.instance.defaultPath('${safe}_E${selected}.mp4');final task=await DownloadManager.instance.start(id:'${widget.title.id}-$selected',title:'${widget.title.name} • Episode $selected',url:s.url,path:path,onChanged:(_){if(mounted)setState((){});});if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Download ${task.status}')));}
  void _saveProgress(){final p=player;if(p==null||!p.value.isInitialized)return;final pos=p.value.position.inMilliseconds,dur=p.value.duration.inMilliseconds;if(dur>0){ProgressStore.save(WatchProgress(titleId:widget.title.id,title:widget.title.name,episode:selected,positionMs:pos,durationMs:dur,updatedAt:DateTime.now().millisecondsSinceEpoch));}}
  @override void dispose(){player?.removeListener(_saveProgress);_saveProgress();player?.dispose();super.dispose();}
  Widget controls(){if(streams.isEmpty)return const SizedBox();return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const SizedBox(height:14),Text('Source / Quality',style:Theme.of(context).textTheme.titleMedium),Wrap(spacing:8,children:List.generate(streams.length,(i)=>ChoiceChip(label:Text([streams[i].quality,streams[i].language].where((x)=>x.isNotEmpty).join(' • ').isEmpty?'Source ${i+1}':[streams[i].quality,streams[i].language].where((x)=>x.isNotEmpty).join(' • ')),selected:streamIndex==i,onSelected:(_){setState(()=>streamIndex=i);_openStream(streams[i]);}))),if(streams[streamIndex].subtitles.isNotEmpty)...[const SizedBox(height:10),Text('Subtitles',style:Theme.of(context).textTheme.titleMedium),...streams[streamIndex].subtitles.map((x)=>ListTile(dense:true,leading:const Icon(Icons.subtitles),title:Text(x),onTap:()=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Subtitle track: $x')))))]]);}
  @override Widget build(BuildContext context){final p=player;return Scaffold(appBar:AppBar(title:Text(widget.title.name)),body:ListView(padding:const EdgeInsets.all(14),children:[AspectRatio(aspectRatio:16/9,child:Container(decoration:BoxDecoration(color:Colors.black,borderRadius:BorderRadius.circular(12)),child:p!=null&&p.value.isInitialized?ClipRRect(borderRadius:BorderRadius.circular(12),child:Stack(alignment:Alignment.bottomCenter,children:[VideoPlayer(p),VideoProgressIndicator(p,allowScrubbing:true)])):Center(child:IconButton(iconSize:72,onPressed:play,icon:const Icon(Icons.play_circle_fill))))),if(message.isNotEmpty)Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Text(message)),const SizedBox(height:12),Text(widget.title.name,style:Theme.of(context).textTheme.headlineSmall),if(widget.title.overview.isNotEmpty)Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Text(widget.title.overview)),Row(children:[Expanded(child:FilledButton.icon(onPressed:play,icon:const Icon(Icons.play_arrow),label:const Text('Play'))),IconButton(onPressed:download,icon:const Icon(Icons.download_outlined)),PopupMenuButton<double>(onSelected:(v){setState(()=>speed=v);player?.setPlaybackSpeed(v);},itemBuilder:(_)=>[.75,1,1.25,1.5,2].map((v)=>PopupMenuItem(value:v,child:Text('${v}x'))).toList(),child:const Padding(padding:EdgeInsets.all(12),child:Icon(Icons.speed)))]),controls(),const SizedBox(height:18),Text('Episodes',style:Theme.of(context).textTheme.titleLarge),if(loading)const Padding(padding:EdgeInsets.all(20),child:Center(child:CircularProgressIndicator())) else Wrap(spacing:8,runSpacing:8,children:eps.map((e)=>ChoiceChip(label:Text('${e.number}'),selected:selected==e.number,onSelected:(_){setState(()=>selected=e.number);player?.pause();streams=[];})).toList())]);}
}
