// ignore_for_file: prefer_const_literals_to_create_immutables, prefer_const_constructors
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import '../../core/api.dart'; import '../../core/downloads.dart';
class DownloadsPage extends StatefulWidget{const DownloadsPage({super.key,required this.api});final ApiClient api;@override State<DownloadsPage> createState()=>_DownloadsPageState();}
class _DownloadsPageState extends State<DownloadsPage>{Timer? timer;@override void initState(){super.initState();timer=Timer.periodic(const Duration(milliseconds:500),(_){if(mounted)setState((){});});}@override void dispose(){timer?.cancel();super.dispose();}
 @override Widget build(BuildContext context){final items=DownloadManager.instance.tasks.values.toList();if(items.isEmpty)return ListView(padding:const EdgeInsets.all(16),children:[const SizedBox(height:60),Image(image:AssetImage('assets/images/bottom_bar/download.png'),height:70),const SizedBox(height:18),const Center(child:Text('No downloads yet')),const SizedBox(height:8),const Center(child:Text('Downloaded videos and active tasks will appear here.'))]);return ListView.builder(padding:const EdgeInsets.all(10),itemCount:items.length,itemBuilder:(_,i){final x=items[i];return Card(child:ListTile(title:Text(x.title),subtitle:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const SizedBox(height:7),LinearProgressIndicator(value:x.progress),const SizedBox(height:4),Text(x.total>0?'${(x.progress*100).toStringAsFixed(1)}% • ${x.status}':x.status)]),trailing:PopupMenuButton<String>(onSelected:(v)async{if(v=='cancel')await DownloadManager.instance.cancel(x.id);if(v=='delete'){await DownloadManager.instance.cancel(x.id);final f=File(x.path);if(await f.exists())await f.delete();DownloadManager.instance.tasks.remove(x.id);}setState((){});},itemBuilder:(_)=>const[PopupMenuItem(value:'cancel',child:Text('Pause')),PopupMenuItem(value:'delete',child:Text('Delete'))])));});}
}
